"""Standard Webhooks verification, driven by vectors the Node SDK produced.

``tests/fixtures/webhook_vectors.json`` is generated by
``scripts/gen_webhook_vectors.mjs``, which mirrors
``DevinoSolutions/shorty-sdk/test/webhooks.test.ts`` scenario for scenario and
signs with Node's ``crypto``. Passing these proves cross-implementation
agreement with the TypeScript SDK and the server signer — a Python
implementation that only passes its own self-generated signatures proves
nothing.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import time
from typing import Any

import pytest

from shorty_py import DEFAULT_TOLERANCE_SECONDS, verify_webhook_signature
from tests.conftest import load_fixture

VECTORS = load_fixture("webhook_vectors.json")
CASES = VECTORS["cases"]

SECRET = "whsec_" + base64.b64encode(b"local-signing-secret-24b").decode()
NOW = 1_753_000_000
WEBHOOK_ID = "msg_local"


def sign(secret: str, content: str) -> str:
    key = base64.b64decode(secret.removeprefix("whsec_"))
    return base64.b64encode(hmac.new(key, content.encode(), hashlib.sha256).digest()).decode()


def headers_for(webhook_id: str, timestamp: object, signature: str) -> dict[str, str]:
    return {
        "webhook-id": webhook_id,
        "webhook-timestamp": str(timestamp),
        "webhook-signature": signature,
    }


# ---------------------------------------------------------------------------
# The ported cross-implementation vectors
# ---------------------------------------------------------------------------


def test_the_vector_file_covers_the_typescript_scenario_matrix() -> None:
    assert len(CASES) == 10
    names = {case["name"] for case in CASES}
    assert "rotation: two signatures, receiver still on the old secret" in names
    assert "reserialized JSON body fails (the raw-byte rule)" in names


@pytest.mark.parametrize("case", CASES, ids=[c["name"] for c in CASES])
def test_node_generated_vector(case: dict[str, Any]) -> None:
    result = verify_webhook_signature(
        payload=case["payload"],
        headers=headers_for(case["webhook_id"], case["timestamp"], case["signature_header"]),
        secret=case["secret"],
        tolerance_seconds=case.get("tolerance_seconds", DEFAULT_TOLERANCE_SECONDS),
        now_seconds=case["now_seconds"],
    )
    assert result.valid is case["expected_valid"], case["name"]
    assert result.reason == case.get("expected_reason"), case["name"]


# ---------------------------------------------------------------------------
# SDK-specific behaviors the TS vectors do not cover
# ---------------------------------------------------------------------------


def test_missing_headers_are_reported_rather_than_treated_as_a_bad_signature() -> None:
    result = verify_webhook_signature(payload="{}", headers={}, secret=SECRET, now_seconds=NOW)
    assert not result
    assert result.reason == "missing_headers"


@pytest.mark.parametrize("missing", ["webhook-id", "webhook-timestamp", "webhook-signature"])
def test_each_individually_missing_header_is_detected(missing: str) -> None:
    body = "{}"
    headers = headers_for(WEBHOOK_ID, NOW, f"v1,{sign(SECRET, f'{WEBHOOK_ID}.{NOW}.{body}')}")
    headers.pop(missing)
    result = verify_webhook_signature(payload=body, headers=headers, secret=SECRET, now_seconds=NOW)
    assert result.reason == "missing_headers"


def test_a_bytes_payload_verifies_identically_to_a_str_payload() -> None:
    body = '{"a":1}'
    signature = f"v1,{sign(SECRET, f'{WEBHOOK_ID}.{NOW}.{body}')}"
    for payload in (body, body.encode(), bytearray(body.encode())):
        result = verify_webhook_signature(
            payload=payload,
            headers=headers_for(WEBHOOK_ID, NOW, signature),
            secret=SECRET,
            now_seconds=NOW,
        )
        assert result.valid, type(payload)


def test_header_lookup_is_case_insensitive_and_accepts_a_list_of_pairs() -> None:
    body = '{"a":1}'
    signature = f"v1,{sign(SECRET, f'{WEBHOOK_ID}.{NOW}.{body}')}"
    upper = {
        "Webhook-Id": WEBHOOK_ID,
        "WEBHOOK-TIMESTAMP": str(NOW),
        "Webhook-Signature": signature,
    }
    assert verify_webhook_signature(
        payload=body, headers=upper, secret=SECRET, now_seconds=NOW
    ).valid

    pairs = [
        ("webhook-id", WEBHOOK_ID),
        ("webhook-timestamp", str(NOW)),
        ("webhook-signature", signature),
    ]
    assert verify_webhook_signature(
        payload=body, headers=pairs, secret=SECRET, now_seconds=NOW
    ).valid


def test_a_multi_value_header_uses_the_first_entry() -> None:
    body = '{"a":1}'
    signature = f"v1,{sign(SECRET, f'{WEBHOOK_ID}.{NOW}.{body}')}"
    headers: dict[str, Any] = {
        "webhook-id": [WEBHOOK_ID, "ignored"],
        "webhook-timestamp": str(NOW),
        "webhook-signature": signature,
    }
    assert verify_webhook_signature(
        payload=body, headers=headers, secret=SECRET, now_seconds=NOW
    ).valid


def test_the_default_tolerance_is_five_minutes() -> None:
    assert DEFAULT_TOLERANCE_SECONDS == 300
    body = "{}"
    stale = NOW - DEFAULT_TOLERANCE_SECONDS - 1
    signature = f"v1,{sign(SECRET, f'{WEBHOOK_ID}.{stale}.{body}')}"
    result = verify_webhook_signature(
        payload=body,
        headers=headers_for(WEBHOOK_ID, stale, signature),
        secret=SECRET,
        now_seconds=NOW,
    )
    assert result.reason == "timestamp_out_of_tolerance"

    just_inside = NOW - DEFAULT_TOLERANCE_SECONDS
    signature = f"v1,{sign(SECRET, f'{WEBHOOK_ID}.{just_inside}.{body}')}"
    assert verify_webhook_signature(
        payload=body,
        headers=headers_for(WEBHOOK_ID, just_inside, signature),
        secret=SECRET,
        now_seconds=NOW,
    ).valid


def test_now_defaults_to_the_wall_clock_when_not_injected() -> None:
    body = "{}"
    now = int(time.time())
    signature = f"v1,{sign(SECRET, f'{WEBHOOK_ID}.{now}.{body}')}"
    assert verify_webhook_signature(
        payload=body, headers=headers_for(WEBHOOK_ID, now, signature), secret=SECRET
    ).valid


@pytest.mark.parametrize("bad", ["", "   ", "not-a-number", "12.5", "1e9", "NaN"])
def test_a_malformed_timestamp_is_reported_as_such(bad: str) -> None:
    result = verify_webhook_signature(
        payload="{}",
        headers=headers_for(WEBHOOK_ID, bad, "v1,AAAA"),
        secret=SECRET,
        now_seconds=NOW,
    )
    assert result.reason == "malformed_timestamp"


@pytest.mark.parametrize(
    "signature",
    ["", "garbage", "v1", "v1,", "v1,!!!not-base64!!!", "v2,abcd", "v1,AAAA"],
)
def test_malformed_signature_tokens_are_rejected_without_raising(signature: str) -> None:
    result = verify_webhook_signature(
        payload="{}",
        headers=headers_for(WEBHOOK_ID, NOW, signature),
        secret=SECRET,
        now_seconds=NOW,
    )
    assert result.reason == "no_matching_signature"


def test_a_secret_without_the_whsec_prefix_is_still_accepted() -> None:
    body = '{"a":1}'
    bare = SECRET.removeprefix("whsec_")
    signature = f"v1,{sign(SECRET, f'{WEBHOOK_ID}.{NOW}.{body}')}"
    assert verify_webhook_signature(
        payload=body,
        headers=headers_for(WEBHOOK_ID, NOW, signature),
        secret=bare,
        now_seconds=NOW,
    ).valid


def test_the_result_is_truthy_for_valid_and_falsy_for_invalid() -> None:
    body = "{}"
    signature = f"v1,{sign(SECRET, f'{WEBHOOK_ID}.{NOW}.{body}')}"
    good = verify_webhook_signature(
        payload=body,
        headers=headers_for(WEBHOOK_ID, NOW, signature),
        secret=SECRET,
        now_seconds=NOW,
    )
    assert good and good.valid and good.reason is None
    bad = verify_webhook_signature(
        payload="tampered",
        headers=headers_for(WEBHOOK_ID, NOW, signature),
        secret=SECRET,
        now_seconds=NOW,
    )
    assert not bad


def test_verification_uses_a_constant_time_comparison() -> None:
    """Pin the implementation: a naive ``==`` here leaks the signature by timing."""
    import inspect

    from shorty_py import webhooks

    source = inspect.getsource(webhooks.verify_webhook_signature)
    assert "hmac.compare_digest" in source
    assert "candidate == expected" not in source
