// Generate cross-implementation webhook vectors using Node's crypto, mirroring
// shorty-sdk/test/webhooks.test.ts scenario-for-scenario. The TS suite mints
// random secrets per run, so there is no committed vector file to copy; these
// are the SAME scenarios, pinned to fixed secrets so the Python verifier is
// proven against signatures produced by the Node implementation.
import { createHmac } from 'node:crypto'

const NOW = 1_753_000_000
const ID = 'msg_123'
// Fixed 24-byte secrets, base64 like the server mints them.
const SECRET_A = 'whsec_' + Buffer.from('shorty-python-vector-a!!').toString('base64')
const SECRET_B = 'whsec_' + Buffer.from('shorty-python-vector-b!!').toString('base64')

function sign(secret, content) {
    const b64 = secret.startsWith('whsec_') ? secret.slice(6) : secret
    const key = new Uint8Array(Buffer.from(b64, 'base64'))
    return createHmac('sha256', key).update(content, 'utf8').digest('base64')
}
const v1 = (secret, id, ts, body) => `v1,${sign(secret, `${id}.${ts}.${body}`)}`

const cases = []
const add = (name, o) => cases.push({ name, webhook_id: ID, now_seconds: NOW, ...o })

{
    const body = '{"event":"job.succeeded","data":{"id":"j1"}}'
    add('valid single signature verifies', {
        payload: body, timestamp: NOW, secret: SECRET_A,
        signature_header: v1(SECRET_A, ID, NOW, body), expected_valid: true,
    })
}
{
    const body = '{"a":1}'
    const content = `${ID}.${NOW}.${body}`
    add('rotation: two signatures, receiver still on the old secret', {
        payload: body, timestamp: NOW, secret: SECRET_A,
        signature_header: `v1,${sign(SECRET_B, content)} v1,${sign(SECRET_A, content)}`,
        expected_valid: true,
    })
}
{
    const body = '{"a":1}'
    add('unknown version tokens (v2,) are ignored, not rejected', {
        payload: body, timestamp: NOW, secret: SECRET_A,
        signature_header: `v2,deadbeef ${v1(SECRET_A, ID, NOW, body)}`,
        expected_valid: true,
    })
}
{
    const body = '{"amount":100}'
    add('tampered body fails', {
        payload: '{"amount":999}', timestamp: NOW, secret: SECRET_A,
        signature_header: v1(SECRET_A, ID, NOW, body),
        expected_valid: false, expected_reason: 'no_matching_signature',
    })
}
{
    const raw = '{ "a": 1, "b": 2 }'
    add('reserialized JSON body fails (the raw-byte rule)', {
        payload: JSON.stringify(JSON.parse(raw)), timestamp: NOW, secret: SECRET_A,
        signature_header: v1(SECRET_A, ID, NOW, raw),
        expected_valid: false, expected_reason: 'no_matching_signature',
    })
}
{
    const body = '{"a":1}'
    const oldTs = NOW - 3600
    add('stale timestamp (older than tolerance) fails', {
        payload: body, timestamp: oldTs, secret: SECRET_A,
        signature_header: v1(SECRET_A, ID, oldTs, body), tolerance_seconds: 300,
        expected_valid: false, expected_reason: 'timestamp_out_of_tolerance',
    })
}
{
    const body = '{"a":1}'
    const futureTs = NOW + 120
    add('future skew within tolerance passes', {
        payload: body, timestamp: futureTs, secret: SECRET_A,
        signature_header: v1(SECRET_A, ID, futureTs, body), expected_valid: true,
    })
}
{
    const body = '{"a":1}'
    add('malformed timestamp header fails', {
        payload: body, timestamp: 'not-a-number', secret: SECRET_A,
        signature_header: v1(SECRET_A, ID, NOW, body),
        expected_valid: false, expected_reason: 'malformed_timestamp',
    })
}
{
    const body = '{"a":1}'
    add('wrong secret fails to match', {
        payload: body, timestamp: NOW, secret: SECRET_B,
        signature_header: v1(SECRET_A, ID, NOW, body),
        expected_valid: false, expected_reason: 'no_matching_signature',
    })
}
{
    const body = '{"unicode":"caf\u00e9 \u2014 na\u00efve"}'
    add('utf-8 body verifies (raw bytes, not code points)', {
        payload: body, timestamp: NOW, secret: SECRET_A,
        signature_header: v1(SECRET_A, ID, NOW, body), expected_valid: true,
    })
}

console.log(JSON.stringify({
    _source: 'Generated by scripts/gen_webhook_vectors.mjs using Node crypto, mirroring DevinoSolutions/shorty-sdk test/webhooks.test.ts scenario-for-scenario. Signatures are produced by the TypeScript/Node implementation, so a Python pass proves cross-implementation agreement, not self-consistency.',
    signed_content: '<webhook-id>.<webhook-timestamp>.<raw-body>, HMAC-SHA256 with base64-decoded secret bytes, header token "v1,<base64>"',
    cases,
}, null, 2))
